modLoader = "javafml"
loaderVersion="[37,)"
license="AGNYA License"
showAsResourcePack=false

[[mods]]
modId="animation_overhaul"
version="${version}"
displayName="Animation Overhaul"
authors="ElocinDev"
description="Overhauls player animations."
logoFile="logo.png"

[[dependencies.animation_overhaul]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"

[[dependencies.animation_overhaul]]
modId="necronomicon"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"